export { default as AdminDashboard } from './Dashboard';
export { AdminUsers } from './Users';
export { default as AdminCourses } from './AdminCourses';
export { default as AdminCertificates } from './AdminCertificates';
export { AdminAnalytics } from './Analytics';
export { AuditLogs } from './AuditLogs';
export { Announcements } from './Announcements';
export { default as AdminKnowledge } from './AdminKnowledge';
export { default as AdminNotifications } from './AdminNotifications';
export { default as Settings } from './Settings';
